<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260825132206 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE diary_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, glycemia_mg_dl INT NOT NULL, measured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ww DOUBLE PRECISION DEFAULT NULL, insulin_dose DOUBLE PRECISION DEFAULT NULL, activity_intensity VARCHAR(255) DEFAULT NULL, activity_duration_minutes INT DEFAULT NULL, insulin_ww_ratio_snapshot DOUBLE PRECISION NOT NULL, base_dose_snapshot DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77B144D1A76ED395 ON diary_entries (user_id)');
        $this->addSql('ALTER TABLE diary_entries ADD CONSTRAINT FK_77B144D1A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE diary_entries DROP CONSTRAINT FK_77B144D1A76ED395');
        $this->addSql('DROP TABLE diary_entries');
    }
}
