<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260825095453 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE patient_profiles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_dose DOUBLE PRECISION NOT NULL, insulin_ww_ratio DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BCB5DD95A76ED395 ON patient_profiles (user_id)');
        $this->addSql('ALTER TABLE patient_profiles ADD CONSTRAINT FK_BCB5DD95A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE patient_profiles DROP CONSTRAINT FK_BCB5DD95A76ED395');
        $this->addSql('DROP TABLE patient_profiles');
    }
}
