<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260826080806 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE base_dose_adjustment_histories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_base_dose INT NOT NULL, new_base_dose INT NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2A630DAA76ED395 ON base_dose_adjustment_histories (user_id)');
        $this->addSql('CREATE TABLE ratio_adjustment_histories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_ratio DOUBLE PRECISION NOT NULL, new_ratio DOUBLE PRECISION NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB73D80DA76ED395 ON ratio_adjustment_histories (user_id)');
        $this->addSql('ALTER TABLE base_dose_adjustment_histories ADD CONSTRAINT FK_A2A630DAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ratio_adjustment_histories ADD CONSTRAINT FK_DB73D80DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE base_dose_adjustment_histories DROP CONSTRAINT FK_A2A630DAA76ED395');
        $this->addSql('ALTER TABLE ratio_adjustment_histories DROP CONSTRAINT FK_DB73D80DA76ED395');
        $this->addSql('DROP TABLE base_dose_adjustment_histories');
        $this->addSql('DROP TABLE ratio_adjustment_histories');
    }
}
